### PR TITLE
fix: typo freelance

### PR DESCRIPTION
**Pull request by thunderfreak**
Fixed a typo.: changed "free lance" --> "freelance" as per issue #5

### CODE REVIEW

**Comment by wimpywarlord** [comment]
@thunderfreak Good work

Could you go through the website and see other typos if present any. And add another commit to this PR. 

It would be a great exercise for you.

**Comment by thunderfreak** [comment]
Sure I will @wimpywarlord

**Comment by thunderfreak** [comment]
I've fixed some more typos. Let me know if they are what you want

**Comment by wimpywarlord** [comment]
GG,

I will select the best PR for merging.

This is the best one so far.

**Pull request closed without merging**
