### PR TITLE
Corrected spelling of freelance

### PR DESCRIPTION
**Pull request by VARUNvk1729**

### CODE REVIEW

**Comment by wimpywarlord** [comment]
Add a description of your contribution

**Comment by AnirudhPanda** [comment]
> Add a description of your contribution

Don't promote this type of PR's man!

**Comment by wimpywarlord** [comment]
@AnirudhPanda It's for beginners.

**Comment by wimpywarlord** [comment]
Issue already resolved, thanks for the effort.

**Pull request closed without merging**
